"""Luật chuyên gia mặc định — tách riêng để giữ expert_system gọn."""


def default_rules() -> list[dict]:
    """Luật khởi tạo theo tri thức miền CNTT và dữ liệu thực tế."""
    return [
        {
            "name": "DS - Thống kê cao",
            "description": "Điểm Thống kê cơ bản >= 80 → tăng Khoa học Dữ liệu",
            "conditions": [
                {"course": "Basic Statistics", "operator": ">=", "value": 90},
                {"course": "Linear Algebra", "operator": ">=", "value": 82},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATA SCIENCE",
            "weight": 0.14,
            "active": True,
        },
        {
            "name": "DS - Đại số tuyến tính cao",
            "description": "Điểm Đại số tuyến tính >= 82 → tăng Khoa học Dữ liệu",
            "conditions": [{"course": "Linear Algebra", "operator": ">=", "value": 82}],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATA SCIENCE",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "DS - Toán cao",
            "description": "Đại số tuyến tính >= 82 VÀ Giải tích >= 90 → tăng Khoa học Dữ liệu",
            "conditions": [
                {"course": "Linear Algebra", "operator": ">=", "value": 82},
                {"course": "Calculus", "operator": ">=", "value": 90},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATA SCIENCE",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "IS - AI cao",
            "description": "Điểm AI >= 90 → tăng Hệ thống Thông minh",
            "conditions": [{"course": "Artificial Intelligence", "operator": ">=", "value": 90}],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "INTELLIGENT SYSTEM",
            "weight": 0.08,
            "active": True,
        },
        {
            "name": "IS - AI + Thuật toán",
            "description": "AI >= 90 VÀ Thiết kế thuật toán >= 78 → tăng Hệ thống Thông minh",
            "conditions": [
                {"course": "Artificial Intelligence", "operator": ">=", "value": 90},
                {"course": "Algorithm Design and Analysis", "operator": ">=", "value": 78},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "INTELLIGENT SYSTEM",
            "weight": 0.08,
            "active": True,
        },
        {
            "name": "IS - AI + Mạng",
            "description": "AI >= 90 VÀ Mạng máy tính >= 78 → tăng Hệ thống Thông minh",
            "conditions": [
                {"course": "Artificial Intelligence", "operator": ">=", "value": 90},
                {"course": "Computer Networks", "operator": ">=", "value": 78},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "INTELLIGENT SYSTEM",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "NET - Mạng rất cao",
            "description": "Điểm Mạng máy tính >= 90 → tăng Công nghệ Mạng",
            "conditions": [{"course": "Computer Networks", "operator": ">=", "value": 90}],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "NETWORK TECHNOLOGY",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "NET - HĐH + Mạng rất cao",
            "description": "Hệ điều hành >= 70 VÀ Mạng >= 90 → tăng Công nghệ Mạng",
            "conditions": [
                {"course": "Operating System", "operator": ">=", "value": 70},
                {"course": "Computer Networks", "operator": ">=", "value": 90},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "NETWORK TECHNOLOGY",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "DB - CSDL rất cao",
            "description": "Điểm Công nghệ CSDL >= 90 → tăng Công nghệ CSDL",
            "conditions": [{"course": "Database Technology", "operator": ">=", "value": 90}],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATABASE TECHNOLOGY",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "DB - CSDL + OOP",
            "description": "CSDL >= 90 VÀ OOP >= 85 → tăng Công nghệ CSDL",
            "conditions": [
                {"course": "Database Technology", "operator": ">=", "value": 90},
                {"course": "Object Oriented Programming", "operator": ">=", "value": 85},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATABASE TECHNOLOGY",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "DB - CSDL + CTDL",
            "description": "CSDL >= 90 VÀ Cấu trúc dữ liệu >= 75 → tăng Công nghệ CSDL",
            "conditions": [
                {"course": "Database Technology", "operator": ">=", "value": 90},
                {"course": "Data Structures", "operator": ">=", "value": 75},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "DATABASE TECHNOLOGY",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "IoT - Mạng + CSDL chuẩn",
            "description": "Mạng máy tính >= 82 VÀ CSDL >= 88 → tăng IoT",
            "conditions": [
                {"course": "Computer Networks", "operator": ">=", "value": 82},
                {"course": "Database Technology", "operator": ">=", "value": 88},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "INTERNET OF THINGS",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "IoT - Mạng + CSDL mở rộng",
            "description": "Mạng máy tính >= 85 VÀ CSDL >= 85 → tăng IoT",
            "conditions": [
                {"course": "Computer Networks", "operator": ">=", "value": 85},
                {"course": "Database Technology", "operator": ">=", "value": 85},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "INTERNET OF THINGS",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "GAME - Web + OOP",
            "description": "Web >= 78 VÀ OOP >= 78 → tăng Công nghệ Game",
            "conditions": [
                {"course": "Web Development", "operator": ">=", "value": 85},
                {"course": "Object Oriented Programming", "operator": ">=", "value": 85},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "GAME TECHNOLOGY",
            "weight": 0.06,
            "active": False,
        },
        {
            "name": "GAME - ATP + CTDL + Mạng",
            "description": "Thuật toán và Lập trình >= 80 VÀ Cấu trúc dữ liệu >= 82 VÀ Mạng máy tính >= 80 → tăng Công nghệ Game",
            "conditions": [
                {"course": "Algorithm and Programming", "operator": ">=", "value": 82},
                {"course": "Data Structures", "operator": ">=", "value": 82},
                {"course": "Computer Networks", "operator": ">=", "value": 80},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "GAME TECHNOLOGY",
            "weight": 0.22,
            "active": True,
        },
        {
            "name": "GAME - Web + OOP + ATP",
            "description": "Web >= 80 VÀ OOP >= 90 VÀ Thuật toán và Lập trình >= 85 → tăng Công nghệ Game",
            "conditions": [
                {"course": "Web Development", "operator": ">=", "value": 82},
                {"course": "Object Oriented Programming", "operator": ">=", "value": 90},
                {"course": "Algorithm and Programming", "operator": ">=", "value": 86},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "GAME TECHNOLOGY",
            "weight": 0.18,
            "active": False,
        },
        {
            "name": "SE - Thiết kế chương trình",
            "description": "Program Design Methods >= 88 VÀ OOP >= 85 → tăng Kỹ thuật Phần mềm",
            "conditions": [
                {"course": "Program Design Methods", "operator": ">=", "value": 88},
                {"course": "Object Oriented Programming", "operator": ">=", "value": 85},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "SOFTWARE ENGINEERING",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "SE - OOP cao",
            "description": "OOP >= 90 → tăng Kỹ thuật Phần mềm",
            "conditions": [{"course": "Object Oriented Programming", "operator": ">=", "value": 90}],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "SOFTWARE ENGINEERING",
            "weight": 0.12,
            "active": True,
        },
        {
            "name": "SE - Thuật toán + CTDL + OOP",
            "description": "Thuật toán và Lập trình >= 88 VÀ Cấu trúc dữ liệu >= 80 VÀ OOP >= 85 → tăng Kỹ thuật Phần mềm",
            "conditions": [
                {"course": "Algorithm and Programming", "operator": ">=", "value": 88},
                {"course": "Data Structures", "operator": ">=", "value": 80},
                {"course": "Object Oriented Programming", "operator": ">=", "value": 85},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "SOFTWARE ENGINEERING",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "SE - Thuật toán cao",
            "description": "Thuật toán và Lập trình >= 90 VÀ Phương pháp thiết kế CT >= 80 → tăng Kỹ thuật Phần mềm",
            "conditions": [
                {"course": "Algorithm and Programming", "operator": ">=", "value": 90},
                {"course": "Program Design Methods", "operator": ">=", "value": 80},
            ],
            "logic": "AND",
            "action_type": "boost",
            "target_major": "SOFTWARE ENGINEERING",
            "weight": 0.18,
            "active": True,
        },
        {
            "name": "Loại trừ AI yếu cho IS",
            "description": "Điểm AI < 55 → loại trừ Hệ thống Thông minh",
            "conditions": [{"course": "Artificial Intelligence", "operator": "<", "value": 55}],
            "logic": "AND",
            "action_type": "exclude",
            "target_major": "INTELLIGENT SYSTEM",
            "weight": 0.0,
            "active": False,
        },
    ]
